// TYPES NOTE
export const FETCH_NOTE_REQUEST = "FETCH_NOTE_REQUEST";
export const FETCH_NOTE_SUCCEEDED = "FETCH_NOTE_SUCCEEDED";

export const CREATE_NOTE_REQUEST = "CREATE_NOTE_REQUEST";
export const CREATE_NOTE_SUCCEEDED = "CREATE_NOTE_SUCCEEDED";

export const DELETE_NOTE_REQUEST = "DELETE_NOTE_REQUEST";
export const DELETE_NOTE_SUCCEEDED = "DELETE_NOTE_SUCCEEDED";

export const EDIT_NOTE_REQUEST = "EDIT_NOTE_REQUEST";
export const EDIT_NOTE_SUCCEEDED = "EDIT_NOTE_SUCCEEDED";

export const FETCH_NOTE_DETAIL_REQUEST = "FETCH_NOTE_DETAIL_REQUEST";
export const FETCH_NOTE_DETAIL_SUCCEEDED = "FETCH_NOTE_DETAIL_SUCCEEDED";

export const FETCH_NOTE_DETAIL_LOCAL_SUCCEEDED = "FETCH_NOTE_DETAIL_LOCAL_SUCCEEDED";

export const NOTE_LOADING = "NOTE_LOADING";
export const NOTE_LOADED = "NOTE_LOADED";

export const COMMENT_NOTE_REQUEST = "COMMENT_NOTE_REQUEST";
export const COMMENT_NOTE_SUCCEEDED = "COMMENT_NOTE_SUCCEEDED";

// TYPES AUTH + USER
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCEEDED = "GET_USER_SUCCEEDED";

export const GOOGLE_LOGIN_REQUEST = "GOOGLE_LOGIN_REQUEST";
export const GOOGLE_LOGIN_SUCCEEDED = "GOOGLE_LOGIN_SUCCEEDED";

export const TWITTER_LOGIN_REQUEST = "TWITTER_LOGIN_REQUEST";
export const TWITTER_LOGIN_SUCCEEDED = "TWITTER_LOGIN_SUCCEEDED";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCEEDED = "USER_LOGOUT_SUCCEEDED";

export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOADED = "AUTH_LOADED";

export const AUTHENTICATE_REQUEST = "AUTHENTICATE_REQUEST";
export const AUTHENTICATE_SUCCEEDED = "AUTHENTICATE_SUCCEEDED";
export const AUTHENTICATE_FAILED = "AUTHENTICATE_FAILED";

// TYPES ERROR
